name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Test vim script
      run: bash -c 'make setup && make test'
